### ISSUE TITLE
Typo: "allergo"

### ISSUE THREAD

**Issue by Hexstream** [compufox/with-user-abort#1]
I'm not familiar with Allegro, but I'm assuming that "#+allergo" should be "#+allegro".

**edit:** Also, I would put the package stuff in `package.lisp` and the main code in `main.lisp`.

**edit 2:** Also, "recieved" should be "received".

**Comment by compufox** [comment]
Heh, thanks for the typo catches!

I also wasn't sure if I should split it up into a separate package definition file and logic file since the code was so few lines.

Thank you for going through this repo and opening issues! I appreciate it!
