### ISSUE TITLE
For LispWorks, add #+lispwroks conditions:keyboard-break

### ISSUE THREAD

**Issue by Yehouda** [compufox/with-user-abort#4]
https://github.com/compufox/with-user-abort/blob/60693b4a1354faf17107ad6003b0b870cca37081/main.lisp#L3

The type of the condition for user keyboard interrupt is **conditions:keyboard-break**, so you can add it to the conditionalization.

You can avoid repetition by defining a function to get  the symbol:
```
(eval-when (compile load eval) ; make it defined at read time too

(defun get-system-interrupt-condition-type ()
  (quote
   #+sbcl sb-sys:interactive-interrupt
   #+ccl ccl:interrupt-signal-condition
   #+clisp system::simple-interrupt-condition
   #+ecl ext:interactive-interrupt
   #+allegro excl:interrupt-signal
   #+lispworks conditions:keyboard-break)
  ))
```
and then use it with #.:
```



(define-condition user-abort (#.(get-system-interrupt-condition-type))
  ()
  (:documentation "condition that inherits from implementation specific interrupt condition"))




(defmacro with-user-abort (&body body)
  "execute BODY, signalling user-abort if the interrupt signal is received"
  `(handler-bind ((#.(get-system-interrupt-condition-type)
		   #'user-abort))
     ,@body))


```

**Comment by compufox** [comment]
Sorry for not fixing this issue sooner. I just saw it now.

I just pushed a change that adds the lispworks condition as you have outlined, and also implements the changes you suggested (thanks for that by the way! this was one of the first lisp packages I wrote lol).
